/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Decrypted {
  sk: string
  isGm: boolean
}
export function decryptFilekey(filekey: string, password: string): Decrypted
